#!/usr/bin/env bash
# This script kills the "To infinity and beyond" program using sigkill signal.

# Get the PID of the program
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# Terminates the infinite process
if [ -n "$id" ]
then
	kill -15 "$id"
fi
